### ISSUE TITLE
String representation of the model use too much space in TabularInline

### ISSUE THREAD

**Issue by vstoykov** [divio/djangocms-admin-style#354]
When String representation of an object is a little bit longer and TabularInline is used then a lot of space is wasted and become a problem for small monitors and devices.

This is how it looks in Django's normal admin:
![django_tabular_inline_django1 8](https://cloud.githubusercontent.com/assets/902381/16339306/9d3d0ccc-3a2a-11e6-95de-32636fbd4f81.png)

This is how it looks with the new Flat theme:
![django_tabularinline_flat](https://cloud.githubusercontent.com/assets/902381/16339315/ae4a07a4-3a2a-11e6-9d97-aaf83e3560f1.png)

And this is how it looks with DjangoCMS's theme:
![django_tabular_inline_cms_style](https://cloud.githubusercontent.com/assets/902381/16339330/c00cc738-3a2a-11e6-8e8f-6a50a5d7ca58.png)

**Comment by FinalAngel** [comment]
thanks for the feedback! @vstoykov would you be able to propose a PR fix?

**Comment by vstoykov** [comment]
I'm better at backend and not so good at frontend. But from what I saw styles for all tables are mixed here probably for DRY but this cause a lot of conflicts especially with the large usage of `!important`.

In order this to be fixed cleanly I think that a lot of stuff need to be changed in `https://github.com/divio/djangocms-admin-style/blob/master/djangocms_admin_style/sass/components/_tables.scss` in order not to break other tables.

I'll try to see if I can get the dev environment up and running and see if a can change some SASS.

**Comment by lory87** [comment]
@vstoykov I merged the fixes to master. Thank you for your feedback.

**Comment by vstoykov** [comment]
@lory87 The problem is not fixed.

After latest changes in master now it looks like this:
![djangocms-admin-style-tabular-still-broken](https://cloud.githubusercontent.com/assets/902381/16409375/dfebba8e-3d25-11e6-80ea-1ebb14807f9c.png)

And it probably should look something like this:
![djangocms-admin-style-tabular-fixed](https://cloud.githubusercontent.com/assets/902381/16409386/ebbfc95e-3d25-11e6-8405-3af3c41e160d.png)

**Comment by lory87** [comment]
@vstoykov I fixed the select field width and merged the changes to master.

**Comment by vstoykov** [comment]
Thanks!

Nevertheless I think that this issue must be reopened because the main problem persists.

 In my last screenshot for how probably it need to looks like, I've showed similar look to django's own admin theme. String representation of the instance is above the fields not in line with them. In this case there will be enough space for the fields especially on smaller screens. 

Changes that I've proposed in #357 implement this behavior. You can look at them for inspiration.

**Comment by lory87** [comment]
Hi @vstoykov 
I aligned the table content on top. Textarea field height is reverted. Now it looks like on previous versions or without admin style. Thank you for your feedback.

**Comment by vstoykov** [comment]
Thanks @lory87  tabular inlines looks better with vertical align top instead of middle.

One last thing is left (which was the reason to open the issue) the string representation of the instance is taking too much horizontal space. In the original django theme it is above  the fields. Now with vertical align top is easy to return the original `padding-top` from django's theme and move the `td.original > p` in this padding and then `td.original` will no longer take extra space.

**Comment by vxsx** [comment]
I believe https://github.com/divio/djangocms-admin-style/pull/374 this one should finally fix the original issue

**Comment by vstoykov** [comment]
I upgraded to 1.2.5 and removed my extra css styles related to this and now it looks ok. I'm closing the issue.
